### ISSUE TITLE
Server Type always says "z/OS"

### ISSUE THREAD

**Issue by dkelosky** [dkelosky/js-osFtp#44]
Create / edit a site and alter the "Server Type" to something besides "z/OS".  Save and close and relaunch to observe that the Server Type is set again to "z/OS".

**Comment by nikitogr** [comment]
Linux and Windows aren't supported (yet I assume)

**Comment by ldl5007** [comment]
As of right now there server type stuck as "z/OS".  But if your linux server support 'site' command then it will still work.  I have not tested with Windows server.

**Comment by nikitogr** [comment]
At least mine didn't work in a linux server.

**Comment by ldl5007** [comment]
Please hit F12 to turn on the debug console to see what is failing. If you can provide us the problem, then I can try to fix.  Thank you for using the extension.

**Comment by dkelosky** [comment]
Any update on this?  I know we're both out on vacation, but it would be cool to get this fixed for next time.

**Comment by ldl5007** [comment]
new pushed, the server type are now being remember when you changed the value.  This change does not affecting how the ftp is being perform.  It still making the assumption that your FTP server supporting site command.  I will keep this issue open just because I want to revisit it later when I have more time to test how it going to work on a Linux and Windows FTP server
